condition.plugin.node_has_implicit_parent:
  type: condition.plugin
  mapping:
    model_uri:
      type: text
      label: 'Model Taxonomy Term URI'
    parent_reference_field:
      type: string
      label: 'Parent reference field'
    uri:
      type: text
      label: 'Taxonomy Term URI'
    logic:
      type: string
      label: 'Logic (AND or OR)'
